### ISSUE TITLE
TypeError: Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by souhailmerroun** [vn38minhtran/react-modal-bootstrap#17]
![image](https://user-images.githubusercontent.com/8895242/32501431-dea45e74-c3cf-11e7-9d7a-4b76b9d2ab1d.png)

**Comment by sky-xo** [comment]
I'm getting this error as well. :-/

**Comment by souhailmerroun** [comment]
I ended up using just CSS for the modal. You can check my component in here https://github.com/fleetl/fleetl-web-app/blob/master/src/components/SkillModalComponent.js

**Comment by Shaun2D2** [comment]
this is an issue with proptypes.  React 16 removed them from the react package and expects them to be pulled in from the prop-types package.  It appears a PR has already been submitted and is waiting for approval #14
