### ISSUE TITLE
Warning in React 15.2.0

### ISSUE THREAD

**Issue by wirmar** [vn38minhtran/react-modal-bootstrap#6]
Warning: Unknown prop `_radiumDidResolveStyles` on `<div>` tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    \* in div (created by Modal)
    \* in Modal (created by ...

React 15.2.0 added warnings for unsupported props on native DOM components. Such a warning appears when using react-modal-bootstrap.

**Comment by minhtranite** [comment]
Relative to https://github.com/FormidableLabs/radium/issues/759

**Comment by wirmar** [comment]
radium issue is fixed in Release 0.18.0: https://github.com/FormidableLabs/radium/blob/master/CHANGELOG.md#0180-july-15-2016

Would you consider updating the dependency?

**Comment by minhtranite** [comment]
Fixed in new release https://github.com/vn38minhtran/react-modal-bootstrap/releases/tag/v1.1.0
