### ISSUE TITLE
React warning when passing valid bootstrap modal size class - modal-md

### ISSUE THREAD

**Issue by rayno** [vn38minhtran/react-modal-bootstrap#7]
This is valid bootstrap class and modal is rendered properly.
Yet the component raises a warning 

```
Warning: Failed propType: Invalid prop `size` of value `modal-md` supplied to `Modal`, expected one of ["modal-lg","modal-sm",""]. Check the render method of `ModalDialog`.
```

Great component BTW!

**Comment by minhtranite** [comment]
Bootstrap modal have two [optional sizes](http://getbootstrap.com/javascript/#modals-sizes) is `modal-lg` and `modal-sm`. It seems `modal-md` is default size so you don't need pass it

**Comment by rayno** [comment]
Thanks!
